spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

    show-sql: true

server:
  port: 8080

frontend:
  url: ${FRONT_URL}  

jwt:
  secret: ${JWT_SECRET}

encryption:
  key: ${ENCRYPTION_KEY}
  algorithm: AES